#!/bin/bash
#Backup data per month, delete the data longer than one month.

#bak_cycle=35 #The backup cycle is 30 days.
#full_bak_cycle=7 #Full backup every week.
#diff_bak_cycle=1 #Difference backup everyday
#rm_cycle=35 #The deletion cycle is 30 days.
source_path=/usr/local/src/goal
backup_date=`date '+%Y%m%d'`
if [ `date '+%w'` -eq 3 ]#周三执行删除动作
then
for i in `seq 1 7`
do rm -rf `date -d "-$i day" +%Y%m%d`.tar#清理删除一周前的备份
done
rm -rf bak
fi
tar -g bak -cPzf $backup_date.tar $source_path#带路径备份文件
